# Linear Algebra Review

This page reviews some basic linear algebra for machine learning.

## Overview
- Vectors
    - definition
    - norm of a vector
    - operations
    - dot products
- Matrices
    - definition
    - operations

***

## Vectors

Tuple of real numbers.

- $V=[V_1, V_2, ... V_d]$

- $V_1, V_2,,$ are components of vector $V$.

This vector has $d$ members; hence, this vector's dimension is $d$.

Dimension of the vector is represented as follows:

- $V  \in \mathbb{R}^d$

###  Example vector, d=2

<div>
<img src="figures/vector_ex.png" width="300"/>
</div>


An example vector $a=[2,3]$.

We use $x$ and $y$ as convention, but we can draw and denote as $x_1$ and $x_2$ for 2 dimensional vector space.

A vector has magnitude and direction.

Length of this vector is $\sqrt{2^2 + 3^2}$

$\tan \theta$ of the vector is $\frac{3}{2}$

### Norm of a vector

*Norm* is a length or size of the vector in the vector space.


- $V=[V_1, V_2, ... V_d]$

- $V_1, V_2,,$ are components of vector $V$.

- Norm is shown as double bar, $||V||$, and it is a scalar value, i.e $||V|| \in \mathbb{R}$

There are different types of norms. We will introduce $l^2$ norm (read l 2 norm) also known as euclidean norm.

- $||V||_2 = \sqrt{V_1^2 + V_2^2 + ... + V_d^2} = \sqrt{\sum_{i=1}^d V_i^2}$


### Operations of vectors

#### Element-wise operations

Apply operations (sum, subtractions, ...) element by element of vectors.

- $a, b \in \mathbb R^d$
- $c = a + b$

The result $c$ is also $d$ dimension, $c \in \mathbb R ^d$


The following shows the element-wise operation.

- $c_i = a_i + b_i$ for $i=0, .. d$
- $c = [a_1+b_1, a_2+b_2, ... a_d+b_d]$


The following is an example of `numpy` code.

In [4]:
# elementwise operstion example

import numpy as np

y = np.array([1,2,3])
x = np.array([2,3,4])

print(y + x) # [3, 5, 7]
print(y + x) # [3, 5, 7]
print(y - x) # [-1, -1, -1]
print(y / x) # [.5, .67, .75]

[3 5 7]
[3 5 7]
[-1 -1 -1]
[0.5        0.66666667 0.75      ]


#### Scalar multiplications

Apply scalar value to all vector elements.

- $V \in \mathbb R^d$, $k \in \mathbb R$
- $c = k V$

The result $c$ is also $d$ dimension, $c \in \mathbb R ^d$


The following shows the element-wise operation.

- $c_i = k V_i$ for $i=0, .. d$
- $c = [kV_1, kV_2, ... kV_d]$




#### Dot product

Dot product is ths sum of the products of each element of two vectors. The output of the dot product of two vectors are scalar.

- $a, b \in \mathbb R^d$
- $c = a \cdot b$

The output of the dot product of two vectors are scalar, $c \in \mathbb R$


The following shows the dot product.

- $c = \sum_{i=1}^d a_i b_i$

- $c = a_1b_1 +  a_2b_2, ..., + a_db_d$



When divided by magnitude of two vectors, then it is cosine similarity, which is a way to measure how two vectors are close to each other.



## Matrices

Matrices can be defined as a tuple of vectors.

We have the $m$ vectors.

- $P_1, P_2, ..., P_m \in \mathbb R^n$


We can define a matrix with the above vectors in the dimension of $m$ row, $n$ columns.

$P$ = $\begin{bmatrix}
  <- P_1 -> \\ 
  <- P_2 -> \\
  ... \\
  <- P_m ->
\end{bmatrix}$

- $P \in \mathbb R^{mxn}$, here $m$ is number of row, $n$ number of columns.

In [10]:
# matrix example

a = np.array([
 [1,2,3],
 [4,5,6]
])

print("mat a:\n {}".format(a))
print("dim of mat a: {}".format(a.shape))

a.shape == (2,3)
b = np.array([
 [1,2,3]
])

b.shape == (1,3)

mat a:
 [[1 2 3]
 [4 5 6]]
dim of mat a: (2, 3)


True

### Matrix - vector product

Matrix and vector product is defined as follows:

- $P \in \mathbb R^{mxn}$
- $v \in \mathbb R^n$



- $a = P v$,  Note that $n$ should be the same



- $a = [P_1 \cdot v, P_2 \cdot v, P_m \cdot v]$

- $a \in \mathbb R^m$


$P$ = $\begin{bmatrix}
  <- P_1 -> \\ 
  <- P_2 -> \\
  ... \\
  <- P_m ->
\end{bmatrix}$


In [24]:
P = np.array([
 [1,2,3],
 [4,5,6]
])

v = np.array(
 [1,2,3])

print("mat P:\n {}".format(P))
print("dim of mat P: {}".format(P.shape))
print("mat v:\n {}".format(v))
print("dim of mat v: {}".format(v.shape))

c=P@v # @ dot product, '*' in numpy is element-wise operation, and it might broadcast based on the dimensions
print("=====")
print("mat c:\n {}".format(c))
print("dim of mat c: {}".format(c.shape))

mat P:
 [[1 2 3]
 [4 5 6]]
dim of mat P: (2, 3)
mat v:
 [1 2 3]
dim of mat v: (3,)
=====
mat c:
 [14 32]
dim of mat c: (2,)


### Matrix multiplications

Matrix multiplications are dot product of rows and columns.

- $P \in \mathbb R^{mxn}$
- $Q \in \mathbb R^{nxk}$



This picture describes matrix multiplications. Element $i$, $j$ of output matrix is the dot product of $i$th row of $a$ and $j$th column of $b$


<div>
<img src="figures/khan_academy_matrix_product.png" width="350"/>
</div>

([image source](https://www.khanacademy.org/math/precalculus/x9e81a4f98389efdf:matrices/x9e81a4f98389efdf:multiplying-matrices-by-matrices/a/multiplying-matrices))

## Credits

This notebook uses the contents from the followring materials:

1. [Linear Algebra Review](https://stanford-cs221.github.io/autumn2021-extra/modules/prerequisites/linear-algebra.pdf)
1. [Linear Algebra](https://ml-cheatsheet.readthedocs.io/en/latest/linear_algebra.html)


***